/* ------------------------------------------------------------------
   Site-wide configuration and content.
   Edit copy here rather than inside components.
   ------------------------------------------------------------------ */

export const SITE = {
  name: "AstroLok",
  // Page titles, descriptions and social metadata live in lib/seo.ts.
  /** Canonical origin. Set NEXT_PUBLIC_SITE_URL in production. */
  url: (process.env.NEXT_PUBLIC_SITE_URL ?? "https://astrolok.app").replace(/\/$/, ""),
  email: "contact@astrolok.app",
  company: "Spacewire Tech",
  year: 2026,
} as const;

/**
 * Single source of truth for the Android CTA.
 * Override with NEXT_PUBLIC_PLAY_STORE_URL without touching code.
 */
export const PLAY_STORE_URL =
  process.env.NEXT_PUBLIC_PLAY_STORE_URL ?? "https://play.google.com/store/apps/details?id=com.spacewire.astrolok";

/** sessionStorage key: set once the visitor has tapped through the welcome intro this session. */
export const INTRO_SESSION_KEY = "astrolok:entered";

export const TRIAL_LINE = "₹3 for a 1-day trial · then ₹249/month · cancel anytime";

export const NAV_ITEMS = [
  { label: "Readings", href: "/#readings" },
  { label: "How it works", href: "/#how-it-works" },
  { label: "Pricing", href: "/#pricing" },
  { label: "FAQ", href: "/#faq" },
  { label: "Contact", href: "/#contact" },
] as const;

/* ------------------------------------------------------------------
   Frame sequences
   ------------------------------------------------------------------ */

export type FrameSequenceName = "palm" | "face" | "astrology" | "chat";

/**
 * Where frame sequences are served from.
 *  - "optimized": WebP files generated by `npm run optimize:frames` (recommended)
 *  - "original":  the untouched source PNGs in /public/frames
 * Set NEXT_PUBLIC_FRAME_SOURCE to switch. Optimized frames automatically fall
 * back to the original PNG if a WebP file is missing.
 */
export const FRAME_SOURCE: "optimized" | "original" =
  process.env.NEXT_PUBLIC_FRAME_SOURCE === "original" ? "original" : "optimized";

export const FRAME_COUNT = 120;

export function getFrameSources(name: FrameSequenceName) {
  const original = { framePath: `/frames/${name}/frame_`, frameExt: "png" };
  if (FRAME_SOURCE === "original") {
    return { ...original, smallFramePath: undefined, fallback: undefined };
  }
  return {
    framePath: `/frames-optimized/${name}/frame_`,
    smallFramePath: `/frames-optimized/${name}/sm/frame_`,
    frameExt: "webp",
    fallback: original,
  };
}

/* ------------------------------------------------------------------
   Readings
   ------------------------------------------------------------------ */

export type ReadingFeature = {
  id: string;
  sequence: FrameSequenceName;
  eyebrow: string;
  title: string;
  body: string;
  cta: string;
  /** Short alt text for the scroll animation (one canvas, not per frame) */
  canvasLabel: string;
  /** One plain sentence describing the reading for screen readers and crawlers; not shown visually */
  seoDescription: string;
  name: string;
  /** One-line hook shown under the name in the readings index */
  teaser: string;
  /** What the visual highlights as the scan progresses */
  stages: readonly string[];
  stagesLabel: string;
  /**
   * Scroll progress (0–1) at which each stage lights up. Defaults to even spacing.
   * Set it when the frames have a clear timeline, so the labels match what is on screen.
   */
  stageAt?: readonly number[];
  /** Small label above the heading, only where the heading doesn't name the feature */
  label?: string;
  /** Short supporting line under the stages */
  note?: string;
  /**
   * Desktop composition. The experiences share one system but not one layout:
   *  - "split":        visual on the right, explanation beside it (palm)
   *  - "portrait":     full-bleed visual, copy anchored bottom-left (face)
   *  - "cosmic":       full-bleed visual, copy above and below the chart (astrology)
   *  - "conversation": phone in the centre, copy left, the chat's steps right (chat)
   */
  layout: "split" | "portrait" | "cosmic" | "conversation";
};

export const READING_FEATURES: readonly ReadingFeature[] = [
  {
    id: "palm-reading",
    sequence: "palm",
    eyebrow: "Palm Reading",
    title: "Aapki Palm kya batati hai?",
    body: "Love, Career, Money aur Marriage ke sanket jaaniye.",
    cta: "Try Palm Reading",
    canvasLabel: "AstroLok palm reading showing palm lines",
    seoDescription:
      "AstroLok Palm Reading looks at your life, heart, head and fate lines and gives personalized insights about love, career, money and marriage.",
    name: "Palm Reading",
    teaser: "What do your palm lines say about you?",
    stages: ["Life Line", "Heart Line", "Head Line", "Fate Line"],
    stagesLabel: "Lines explored",
    layout: "split",
  },
  {
    id: "face-reading",
    sequence: "face",
    eyebrow: "Face Reading",
    title: "Aapka Face kya reveal karta hai?",
    body: "Apne features se Love, Career, Money aur Marriage ke sanket jaaniye.",
    cta: "Try Face Reading",
    canvasLabel: "AstroLok face reading analysis",
    seoDescription:
      "AstroLok Face Reading uses a single photo to give insights based on your facial features, such as your eyes, face shape, nose and lips.",
    name: "Face Reading",
    teaser: "What does your face reveal about you?",
    stages: ["Eyes", "Face Shape", "Nose", "Lips"],
    stagesLabel: "Features explored",
    layout: "portrait",
  },
  {
    id: "astrology",
    sequence: "astrology",
    eyebrow: "Astrology",
    title: "Aapki Kundli kya kehti hai?",
    body: "Apni date of birth se Love, Career, Money aur Life ke sanket jaaniye.",
    cta: "Explore Astrology",
    canvasLabel: "AstroLok astrology and birth chart reading",
    seoDescription:
      "AstroLok Astrology uses your date of birth to create your kundli and personalized astrology insights about life, love and career.",
    name: "Astrology",
    teaser: "What does your birth chart say about your life?",
    stages: ["Life", "Love", "Career"],
    stagesLabel: "Areas explored",
    layout: "cosmic",
  },
  {
    id: "chat-with-astro",
    sequence: "chat",
    eyebrow: "Chat with Astro",
    label: "Chat with Astro",
    title: "Sawaal hai? Astro se poochiye.",
    body: "Love, Marriage, Career ya Future — jo jaana hai, seedha poochiye.",
    cta: "Chat with Astro",
    canvasLabel: "AstroLok Chat with Astro conversation",
    seoDescription:
      "Chat with Astro lets you ask questions about love, marriage, career, relationships and your future in a simple conversation.",
    name: "Chat with Astro",
    teaser: "Have a question? Just ask Astro.",
    stages: ["You ask", "Astro replies", "Follow-up questions"],
    stagesLabel: "In the conversation",
    // Matched to the 120 frames: message sent ~f30, replies from ~f60, follow-up suggestions at the end.
    stageAt: [0.24, 0.5, 0.95],
    layout: "conversation",
  },
] as const;

/* ------------------------------------------------------------------
   How it works
   ------------------------------------------------------------------ */

export const HOW_IT_WORKS_STEPS = [
  {
    number: "01",
    title: "Verify your number",
    body: "Phone number enter karein aur OTP se verify karein.",
  },
  {
    number: "02",
    title: "Add your date of birth",
    body: "Apni date of birth add karein, taaki aapki reading personalized ho.",
  },
  {
    number: "03",
    title: "Hold up your palm or face",
    body: "Palm ya face ki ek photo lijiye aur apni reading paaiye.",
  },
] as const;

/* ------------------------------------------------------------------
   Trust
   ------------------------------------------------------------------ */

export const TRUST_POINTS = [
  {
    title: "Only what we need",
    body: "Phone number, date of birth aur palm/face photo.",
  },
  {
    title: "No passwords",
    body: "Secure sign-in with a one-time OTP.",
  },
  {
    title: "Clear privacy policy",
    body: "See exactly how your information is handled.",
  },
] as const;

/* ------------------------------------------------------------------
   Pricing
   ------------------------------------------------------------------ */

export const PRICING = {
  plan: "1-day trial",
  listPrice: "₹249",
  trialPrice: "₹3",
  renewal: "then ₹249/month by UPI Autopay",
  cta: "Start for ₹3",
  note: "Cancel anytime before the trial ends.",
} as const;

export const PRICING_FEATURES = [
  "Personalized readings",
  "Face & Palm insights",
  "Love & Career insights",
  "Unlimited astro guidance",
] as const;

/* ------------------------------------------------------------------
   FAQ
   ------------------------------------------------------------------ */

export const FAQ_ITEMS = [
  {
    q: "What happens to my photos?",
    a: "Your palm or face photo is used to create your reading. How photos and other personal information are handled is described in our Privacy Policy. For any question about your data, write to contact@astrolok.app.",
  },
  {
    q: "How does AstroLok create my reading?",
    a: "Depending on the reading you choose, AstroLok looks at your palm lines, your facial features or your date of birth, and explains what they traditionally suggest in plain language. Readings are meant for guidance and reflection. They are not scientific predictions.",
  },
  {
    q: "How does the ₹3 trial work?",
    a: "You pay ₹3 to start a 1-day trial with everything in the plan included. Cancel any time before the trial ends and nothing further is charged.",
  },
  {
    q: "What happens after the trial?",
    a: "If you don't cancel before the trial ends, your plan continues at ₹249/month, paid by UPI Autopay.",
  },
  {
    q: "Can I cancel?",
    a: "Yes, any time. Cancel before the trial ends and you won't be charged further. Details are in our Cancellation & Refund policy.",
  },
  {
    q: "What information do I need?",
    a: "Your phone number to receive a one-time code, your date of birth, and a photo of your palm or face. Nothing else is asked for.",
  },
  {
    q: "Can I use both Palm Reading and Face Reading?",
    a: "Yes. The plan includes both face and palm insights, along with personalized readings on love and career.",
  },
  {
    q: "What is Chat with Astro?",
    a: "Chat with Astro lets you ask questions about areas such as love, relationships, career and your future and explore personalized insights through a conversational experience.",
  },
  {
    q: "Is AstroLok professional medical, financial or legal advice?",
    a: "No. AstroLok provides readings for guidance and reflection. They should not be treated as professional advice.",
  },
] as const;

/* ------------------------------------------------------------------
   Footer & legal
   ------------------------------------------------------------------ */

export const FOOTER_TAGLINE = "Palm, Face & Astrology readings — all in your pocket.";

export const FOOTER_LINKS = {
  company: [
    { label: "Home", href: "/" },
    { label: "Contact Us", href: "/contact" },
  ],
  policies: [
    { label: "Privacy Policy", href: "/privacy" },
    { label: "Terms & Conditions", href: "/terms" },
    { label: "Cancellation & Refund", href: "/cancellation-refund" },
    { label: "Shipping & Delivery", href: "/shipping-delivery" },
    { label: "Delete Account", href: "/delete-account" },
  ],
} as const;

export const DISCLAIMER = "Readings are for guidance and reflection, not professional advice.";
